---
- hosts: all
  gather_facts: false
  tasks:
       - name: slurp json
         slurp:
           src: /home/ansibleadm/test.json
         register: mydata
   
       - name: Decode base64 to view data
         debug:
           msg: "{{ mydata.content | b64decode }}"  
         register: output
        
       - name: create directory if it doesn't exist
         file:
           path: "{{ item }}"
           state: directory
           recurse: yes
         with_items:
           - "{{ output | dict2items | json_query('[*].value') | first | json_query('[*].dir')}}"
       - name: create files if it doesn't exist
         file:
           path: "{{ item }}"
           state: touch
         with_items:
           - "{{ output | dict2items | json_query('[*].value') | first | json_query('[*].src')}}"

       - name: copy files to respective directory
         copy:
           src: "{{ item.0 }}"
           dest: "{{ item.1 }}"
           remote_src: true
         with_together:
            - "{{ output | dict2items | json_query('[*].value') | first | json_query('[*].src')}}"
            - "{{ output | dict2items | json_query('[*].value') | first | json_query('[*].dir')}}" 
      # - name: create temp file holder 
      #   file:
      #     path: /tmp/tmp_holder
      #     state: directory

      ##################### BOA ##################
       - name: Create files with content
         copy:
           dest: "{{ item.0 }}.json"
           content: |
               "{{ item.1 }}"
        #   remote_src: true
         with_together:
            - "{{ output | dict2items | json_query('[*].value') | first | json_query('[*].src')}}"
            - "{{ output | dict2items | json_query('[*].value') | first | json_query('[*].dir')}}" 
         register: policy_file
       - name: view list of files
         debug:
            var: policy_file  
